version: '3'
services:
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GOODUSER: bibi
        UID: 501
        MAIL: bidule@univ-orleans.fr
        NOM: "Machin Bidule"
    container_name: my-good-container
    volumes:
    - ./dev:/var/www/html
    ports:
    - "5000:8000"
    environment:
      PHP_IDE_CONFIG: serverName=toto
